CREATE OR REPLACE FUNCTION CHECK_BAIRRO() RETURN TRIGGER AS '
DECLARE
    _IDBAIRRO INTEGER;
BEGIN
    
    SELECT B.id FROM bairro AS B WHERE B.nome LIKE NEW.nome INTO _IDBAIRRO;
    IF  _IDBAIRRO IS NULL
        INSERT INTO bairro(nome,fk_cidade) VALUES (NEW.nome, NEW.fk_cidade)
    END IF;

END
'

CREATE TRIGGER TRIG_CHECK_BAIRRO
    INSTEAD OF INSERT OR UPDATE ON bairro
    FOR EACH ROW
    EXECUTE PROCEDURE CHECK_BAIRRO()