CREATE OR REPLACE FUNCTION CHECK_CIDADE() RETURN TRIGGER AS '
DECLARE
    _IDCIDADE INTEGER;
BEGIN
    
    SELECT C.id FROM cidade AS C WHERE C.nome LIKE NEW.nome INTO _IDCIDADE;
    IF  _IDCIDADE IS NULL
        INSERT INTO cidade(nome,fk_estado) VALUES (NEW.nome, NEW.fk_estado)
    END IF;

END
'

CREATE TRIGGER TRIG_CHECK_CIDADE
    INSTEAD OF INSERT OR UPDATE ON Cidade
    FOR EACH ROW
    EXECUTE PROCEDURE CHECK_CIDADE()