--SEMPRE QUE FOR FEITA UMA ATUALIZACAO NO CONTRATO É ALTERADA A DATA DE ULTIMA MODIFICACAO
CREATE OR REPLACE FUNCTION ALTER_ULT_MOD() RETURNS TRIGGER AS '
  BEGIN
    NEW.data_ult_modif = now();
    RETURN NEW;
  END
  ' LANGUAGE plpgsql;

CREATE TRIGGER TRIG_ATUALIZACAO_CONTRATO
  BEFORE UPDATE  ON contrato
  FOR EACH ROW 
  EXECUTE PROCEDURE ALTER_ULT_MOD();



