--QUERY PARA TESTE DO INDICE EMAIL NA TABELA USUARIO
SELECT U.*,S.*,TS.NOME FROM USUARIO AS U
INNER JOIN SERVICO AS S ON U.ID = S.FK_USUARIO
INNER JOIN SERVICO_SUBTIPO_SERVICO AS SBS ON S.ID = SBS.FK_SERVICO
INNER JOIN SUBTIPO_SERVICO AS SS ON SS.ID = SBS.FK_SUBTIPO_SERVICO
INNER JOIN TIPO_SERVICO AS TS ON TS.ID = SS.FK_TIPO_SERVICO
WHERE 1 = 1
AND U.EMAIL ILIKE '%@GMAIL%'


--QUERY PARA TESTE DO INDICE FK_USUARIO NA TABELA INFO_PROFISSIONAL
SELECT IP.* FROM INFO_PROFISSIONAL AS IP
INNER JOIN SERVICO AS S ON IP.FK_USUARIO = S.FK_USUARIO
INNER JOIN SERVICO_SUBTIPO_SERVICO AS SBS ON S.ID = SBS.FK_SERVICO
INNER JOIN SUBTIPO_SERVICO AS SS ON SS.ID = SBS.FK_SUBTIPO_SERVICO
INNER JOIN TIPO_SERVICO AS TS ON TS.ID = SS.FK_TIPO_SERVICO
WHERE 1 = 1
AND IP.FK_USUARIO IN(10,100,999,10000)


--QUERY PARA TESTE DO INDICE FK_USUARIO NA TABELA CONTATO
SELECT CNT.* FROM CONTATO AS CNT
INNER JOIN SERVICO AS S ON CNT.FK_USUARIO = S.FK_USUARIO
INNER JOIN SERVICO_SUBTIPO_SERVICO AS SBS ON S.ID = SBS.FK_SERVICO
INNER JOIN SUBTIPO_SERVICO AS SS ON SS.ID = SBS.FK_SUBTIPO_SERVICO
INNER JOIN TIPO_SERVICO AS TS ON TS.ID = SS.FK_TIPO_SERVICO
WHERE 1 = 1
AND CNT.FK_USUARIO IN(10,100,999,10000,9999999)


--QUERY PARA TESTE DO INDICE TITULO NA TABELA SERVICO
SELECT S.* FROM SERVICO AS S
INNER JOIN USUARIO AS U ON S.FK_USUARIO = U.ID
INNER JOIN HORARIO_PRESTACAO AS HP ON HP.FK_USUARIO = U.ID
INNER JOIN CONTATO AS C ON C.FK_USUARIO = U.ID
WHERE 1 = 1
AND S.TITULO ILIKE '%DESENVOLVIMENTO%'
OR S.TITULO ILIKE '%FIRMWARE%'

--QUERY PARA TESTE DO INDICE DESCRICAO NA TABELA SERVICO
SELECT S.* FROM SERVICO AS S
INNER JOIN USUARIO AS U ON S.FK_USUARIO = U.ID
INNER JOIN HORARIO_PRESTACAO AS HP ON HP.FK_USUARIO = U.ID
INNER JOIN CONTATO AS C ON C.FK_USUARIO = U.ID
WHERE 1 = 1
AND S.DESCRICAO ILIKE '%SNIFFER%'

--QUERY PARA TESTE DO INDICE FK_USUARIO NA TABELA SERVICO
SELECT S.* FROM SERVICO AS S
INNER JOIN USUARIO AS U ON S.FK_USUARIO = U.ID
INNER JOIN ENDERECO AS E ON U.ID = E.FK_USUARIO
INNER JOIN BAIRRO AS B ON E.FK_BAIRRO = B.ID
INNER JOIN CIDADE AS C ON B.FK_CIDADE = C.ID
INNER JOIN ESTADO AS UF ON C.FK_ESTADO = UF.ID
WHERE 1 = 1
AND (S.FK_USUARIO = 100
     OR S.FK_USUARIO = 9999
     OR S.FK_USUARIO = 15)

--QUERY PARA TESTE DO INDICE FK_SERVICO NA TABELA SERVICO_SUBTIPO_SERVICO
SELECT U.*,S.*, C.NOME, UF.NOME FROM SERVICO AS S
INNER JOIN USUARIO AS U ON S.FK_USUARIO = U.ID
INNER JOIN ENDERECO AS E ON U.ID = E.FK_USUARIO
INNER JOIN BAIRRO AS B ON E.FK_BAIRRO = B.ID
INNER JOIN CIDADE AS C ON B.FK_CIDADE = C.ID
INNER JOIN ESTADO AS UF ON C.FK_ESTADO = UF.ID
INNER JOIN SERVICO_SUBTIPO_SERVICO AS SBS ON S.ID = SBS.FK_SERVICO
WHERE 1 = 1
AND SBS.FK_SERVICO IN (100,11111,1111111,15,1113, 577, 23, 10)

--QUERY PARA TESTE DO INDICE FK_SUBTIPO_SERVICO NA TABELA SERVICO_SUBTIPO_SERVICO
SELECT U.*,S.*, TS.NOME, UF.NOME FROM SERVICO AS S
INNER JOIN USUARIO AS U ON S.FK_USUARIO = U.ID
INNER JOIN ENDERECO AS E ON U.ID = E.FK_USUARIO
INNER JOIN BAIRRO AS B ON E.FK_BAIRRO = B.ID
INNER JOIN CIDADE AS C ON B.FK_CIDADE = C.ID
INNER JOIN ESTADO AS UF ON C.FK_ESTADO = UF.ID
INNER JOIN SERVICO_SUBTIPO_SERVICO AS SBS ON S.ID = SBS.FK_SERVICO
INNER JOIN SUBTIPO_SERVICO AS SS ON SS.ID = SBS.FK_SUBTIPO_SERVICO
INNER JOIN TIPO_SERVICO AS TS ON TS.ID = SS.FK_TIPO_SERVICO
WHERE 1 = 1
AND SBS.FK_SUBTIPO_SERVICO IN (100,11111,1111111,15,1113, 577, 23, 10)


