CREATE FUNCTION CHECK_VALORES() RETURNS TRIGGER AS '
  BEGIN
  IF (NEW.valor <= 0) THEN RAISE EXCEPTION ''ERRO: O VALOR DO SERVICO NAO PODE SER NEGATIVO OU 0'';
  END IF;
  RETURN NULL;
  END
'LANGUAGE PLPGSQL;

CREATE TRIGGER ASSERT_VALOR_SERVICO
  BEFORE INSERT OR UPDATE OF valor ON servico
  FOR EACH ROW
  EXECUTE PROCEDURE CHECK_VALORES();