CREATE FUNCTION INFOPRO_DATAS_INICIO_FIM() RETURNS TRIGGER AS '
BEGIN
IF EXISTS(
      SELECT IP.data_fim, IP.data_inicio 
      FROM info_profissional AS IP
      WHERE IP.data_fim < IP.data_inicio
      )THEN RAISE EXCEPTION''ERRO: A DATA DE FIM DA INFORMACAO PROFISSIONAL NAO DEVE SER MENOR DO QUE A DATA DE INCIO DA INFORMACAO PROFISSIONAL'';
END IF;
RETURN NULL;
END
'
LANGUAGE PLPGSQL;

CREATE TRIGGER ASSERT_INFOPRO_DATAS_INICIO_FIM
AFTER INSERT OR UPDATE OF data_fim,data_inicio ON info_profissional
FOR EACH ROW
EXECUTE PROCEDURE INFOPRO_DATAS_INICIO_FIM();

