--total de registros 9 046 272 (9M 46k 272)
drop schema if exists public cascade;
create schema public;
\i /home/x/TEMP/usuario.sql
\i /home/x/TEMP/usuario2.sql
\i /home/x/TEMP/usuario3.sql
\i /home/x/TEMP/usuario4.sql
\i /home/x/TEMP/usuario5.sql
\i /home/x/TEMP/usuario6.sql
\i /home/x/TEMP/estado.sql
\i /home/x/TEMP/cidade.sql
\i /home/x/TEMP/bairro.sql
\i /home/x/TEMP/endereco.sql
\i /home/x/TEMP/endereco2.sql
\i /home/x/TEMP/endereco3.sql
\i /home/x/TEMP/endereco4.sql
\i /home/x/TEMP/endereco5.sql
\i /home/x/TEMP/endereco6.sql
\i /home/x/TEMP/tipo_contato.sql
\i /home/x/TEMP/contato.sql
\i /home/x/TEMP/contato2.sql
\i /home/x/TEMP/contato3.sql
\i /home/x/TEMP/contato4.sql
\i /home/x/TEMP/contato5.sql
\i /home/x/TEMP/contato6.sql
\i /home/x/TEMP/tipo_info_profissional.sql
\i /home/x/TEMP/tipo_info_profissional2.sql
\i /home/x/TEMP/tipo_info_profissional3.sql
\i /home/x/TEMP/tipo_info_profissional4.sql
\i /home/x/TEMP/tipo_info_profissional5.sql
\i /home/x/TEMP/tipo_info_profissional6.sql
\i /home/x/TEMP/contrato.sql
\i /home/x/TEMP/contrato2.sql
\i /home/x/TEMP/contrato3.sql
\i /home/x/TEMP/contrato4.sql
\i /home/x/TEMP/tipo_servico.sql
\i /home/x/TEMP/subtipo_servico.sql
\i /home/x/TEMP/servico.sql
\i /home/x/TEMP/servico2.sql
\i /home/x/TEMP/servico3.sql
\i /home/x/TEMP/servico4.sql
\i /home/x/TEMP/servico5.sql
\i /home/x/TEMP/servico_subtipo_servico.sql
\i /home/x/TEMP/servico_subtipo_servico2.sql
\i /home/x/TEMP/servico_subtipo_servico3.sql
\i /home/x/TEMP/avaliacao.sql
\i /home/x/TEMP/comentario.sql
\i /home/x/TEMP/dia_semana.sql
\i /home/x/TEMP/horario_prestacao.sql
\i /home/x/TEMP/horario_prestacao2.sql
\i /home/x/TEMP/horario_prestacao3.sql
\i /home/x/TEMP/horario_prestacao4.sql