INSERT INTO cidade(nome, fk_estado) VALUES
	('Abaetetuba', 14),
	('Abaeté', 11),
	('Abaiara', 6),
	('Abreu e Lima', 16),
	('Acari', 20),
	('Acopiara', 6),
	('Afuá', 14),
	('Agrolândia', 24),
	('Agronômica', 24),
	('Alcântaras', 6),
	('Alegrete', 23),
	('Altamira', 14),
	('Alto Araguaia', 13),
	('Alto Santo', 6),
	('Altos', 17),
	('Amaraji', 16),
	('Amaturá', 3),
	('Ampére', 18),
	('Angra dos Reis', 19),
	('Angélica', 12),
	('Anhembi', 26),
	('Antônio João', 12),
	('Aracaju', 25),
	('Aracati', 6),
	('Aracruz', 8),
	('Arambaré', 23),
	('Arapiraca', 2),
	('Araquari', 24),
	('Araranguá', 24),
	('Ararendá', 6),
	('Araricá', 23),
	('Araucária', 18),
	('Araxá', 11),
	('Arcos', 11),
	('Arcoverde', 16),
	('Areado', 11),
	('Arenápolis', 13),
	('Arneiroz', 6),
	('Arroio do Meio', 23),
	('Arroio do Padre', 23),
	('Arroio do Tigre', 23),
	('Arroio dos Ratos', 23),
	('Artur Nogueira', 26),
	('Atibaia', 26),
	('Augusto Pestana', 23),
	('Aurora', 6),
	('Balneário Camboriú', 24),
	('Barbalha', 6),
	('Barcelos', 3),
	('Barra Funda', 23),
	('Barra Mansa', 19),
	('Barra de São Francisco', 8),
	('Barra de São Miguel', 2),
	('Barra do Bugres', 13),
	('Barra do Piraí', 19),
	('Barra do Ribeiro', 23),
	('Barracão', 23),
	('Barras', 17),
	('Barreirinha', 3),
	('Barro', 6),
	('Barroquinha', 6),
	('Barueri', 26),
	('Barão', 23),
	('Batayporã', 12),
	('Baturité', 6),
	('Bayeux', 15),
	('Bebedouro', 26),
	('Bela Vista', 12),
	('Belford Roxo', 19),
	('Belo Horizonte', 11),
	('Belém', 14),
	('Benjamin Constant', 3),
	('Bento Gonçalves', 23),
	('Betim', 11),
	('Bezerros', 16),
	('Bicas', 11),
	('Blumenau', 24),
	('Boa Viagem', 6),
	('Boa Vista', 22),
	('Boca do Acre', 3),
	('Boituva', 26),
	('Bom Jesus', 17),
	('Bom Jesus', 23),
	('Bom Jesus do Itabapoana', 19),
	('Bom Jesus dos Perdões', 26),
	('Bom Retiro do Sul', 23),
	('Bombinhas', 24),
	('Bonito', 12),
	('Boquim', 25),
	('Borba', 3),
	('Bossoroca', 23),
	('Braga', 23),
	('Bragança', 14),
	('Bragança Paulista', 26),
	('Braço do Norte', 24),
	('Brejo Santo', 6),
	('Brejo da Madre de Deus', 16),
	('Breu Branco', 14),
	('Brusque', 24),
	('Butiá', 23),
	('Cabo de Santo Agostinho', 16),
	('Cachoeira do Sul', 23),
	('Cachoeiro de Itapemirim', 8),
	('Cacoal', 21),
	('Caibaté', 23),
	('Caieiras', 26),
	('Camaquã', 23),
	('Camaragibe', 16),
	('Campina Grande', 15),
	('Campina das Missões', 23),
	('Campinápolis', 13),
	('Campo Alegre', 24),
	('Campo Bom', 23),
	('Campo Bonito', 18),
	('Campo Erê', 24),
	('Campo Grande', 12),
	('Campo Maior', 17),
	('Campo Mourão', 18),
	('Campo Novo do Parecis', 13),
	('Campo Verde', 13),
	('Campos Novos', 24),
	('Campos dos Goytacazes', 19),
	('Candelária', 23),
	('Canguçu', 23),
	('Canindé', 6),
	('Canoas', 23),
	('Canoinhas', 24),
	('Canápolis', 11),
	('Capanema', 18),
	('Capivari de Baixo', 24),
	('Capão do Leão', 23),
	('Carangola', 11),
	('Caratinga', 11),
	('Carauari', 3),
	('Careiro', 3),
	('Cariacica', 8),
	('Caridade', 6),
	('Caririaçu', 6),
	('Cariús', 6),
	('Carlinda', 13),
	('Carlos Barbosa', 23),
	('Carmo do Paranaíba', 11),
	('Carnaubais', 20),
	('Carnaúba dos Dantas', 20),
	('Caruaru', 16),
	('Cascavel', 18),
	('Caseiros', 23),
	('Castanheira', 13),
	('Catanduva', 26),
	('Catende', 16),
	('Catunda', 6),
	('Catuípe', 23),
	('Caucaia', 6),
	('Caxias do Sul', 23),
	('Caçador', 24),
	('Cedro', 6),
	('Cerro Branco', 23),
	('Cerro Largo', 23),
	('Chapada', 23),
	('Chapecó', 24),
	('Charqueadas', 23),
	('Chopinzinho', 18),
	('Chuí', 23),
	('Chã de Alegria', 16),
	('Cianorte', 18),
	('Clevelândia', 18),
	('Coari', 3),
	('Cocal', 17),
	('Cocal do Sul', 24),
	('Colatina', 8),
	('Colombo', 18),
	('Colorado do Oeste', 21),
	('Comodoro', 13),
	('Conceição das Alagoas', 11),
	('Conceição do Araguaia', 14),
	('Concórdia', 24),
	('Coreaú', 6),
	('Coromandel', 11),
	('Coronel Fabriciano', 11),
	('Corrente', 17),
	('Corumbá', 12),
	('Corupá', 24),
	('Crateús', 6),
	('Crato', 6),
	('Criciúma', 24),
	('Cristal', 23),
	('Croatá', 6),
	('Cruz Alta', 23),
	('Cruzeiro do Sul', 23),
	('Cruzeta', 20),
	('Cubatão', 26),
	('Cuiabá', 13),
	('Cunha Porã', 24),
	('Curitiba', 18),
	('Curitibanos', 24),
	('Currais Novos', 20),
	('Curuá', 14),
	('Cáceres', 13),
	('Diadema', 26),
	('Dois Irmãos', 23),
	('Dois Vizinhos', 18),
	('Dom Pedrito', 23),
	('Dona Emma', 24),
	('Duque de Caxias', 19),
	('Ecoporanga', 8),
	('Eirunepé', 3),
	('Eldorado', 12),
	('Eldorado do Sul', 23),
	('Elesbão Veloso', 17),
	('Embu das Artes', 26),
	('Encantado', 23),
	('Encruzilhada do Sul', 23),
	('Equador', 20),
	('Erebango', 23),
	('Erechim', 23),
	('Ererê', 6),
	('Escada', 16),
	('Espumoso', 23),
	('Estação', 23),
	('Esteio', 23),
	('Estrela', 23),
	('Estância Velha', 23),
	('Farias Brito', 6),
	('Faro', 14),
	('Farroupilha', 23),
	('Faxinal dos Guedes', 24),
	('Fazenda Rio Grande', 18),
	('Feira de Santana', 5),
	('Flores da Cunha', 23),
	('Floriano', 17),
	('Florianópolis', 24),
	('Forquilha', 6),
	('Forquilhinha', 24),
	('Fortaleza', 6),
	('Fraiburgo', 24),
	('Francisco Beltrão', 18),
	('Frederico Westphalen', 23),
	('Frei Inocêncio', 11),
	('Garanhuns', 16),
	('Garibaldi', 23),
	('Garuva', 24),
	('Gaspar', 24),
	('General Sampaio', 6),
	('Getúlio Vargas', 23),
	('Giruá', 23),
	('Glória do Goitá', 16),
	('Governador Dix-Sept Rosado', 20),
	('Governador Valadares', 11),
	('Granito', 16),
	('Granjeiro', 6),
	('Groaíras', 6),
	('Guaiúba', 6),
	('Guajará-Mirim', 21),
	('Guaporé', 23),
	('Guaramirim', 24),
	('Guarani das Missões', 23),
	('Guarantã do Norte', 13),
	('Guarapuava', 18),
	('Guaratinguetá', 26),
	('Guarujá', 26),
	('Guarulhos', 26),
	('Guiratinga', 13),
	('Herval', 23),
	('Hidrolândia', 6),
	('Hortolândia', 26),
	('Humaitá', 3),
	('Ibaretama', 6),
	('Ibema', 18),
	('Ibiapina', 6),
	('Ibiraiaras', 23),
	('Ibirama', 24),
	('Ibirapuitã', 23),
	('Ibirubá', 23),
	('Igarassu', 16),
	('Igrejinha', 23),
	('Iguaba Grande', 19),
	('Iguatemi', 12),
	('Iguatu', 6),
	('Ijuí', 23),
	('Ilha Grande', 17),
	('Ilhabela', 26),
	('Imbituba', 24),
	('Imbé', 23),
	('Imigrante', 23),
	('Indaial', 24),
	('Independência', 6),
	('Ingá', 15),
	('Ipanema', 11),
	('Ipaporanga', 6),
	('Ipatinga', 11),
	('Iporã do Oeste', 24),
	('Ipu', 6),
	('Ipê', 23),
	('Iracema', 6),
	('Itabaiana', 25),
	('Itabirito', 11),
	('Itaboraí', 19),
	('Itacoatiara', 3),
	('Itaitinga', 6),
	('Itaiópolis', 24),
	('Itajaí', 24),
	('Itajá', 20),
	('Itanhaém', 26),
	('Itapema', 24),
	('Itapipoca', 6),
	('Itapira', 26),
	('Itapissuma', 16),
	('Itaquaquecetuba', 26),
	('Itaqui', 23),
	('Itatinga', 26),
	('Itatira', 6),
	('Itaúba', 13),
	('Itaúna', 11),
	('Ituiutaba', 11),
	('Ituporanga', 24),
	('Ivinhema', 12),
	('Ivoti', 23),
	('Içara', 24),
	('Iúna', 8),
	('Jaboatão dos Guararapes', 16),
	('Jaboticabal', 26),
	('Jacareí', 26),
	('Jacinto Machado', 24),
	('Jaguaretama', 6),
	('Jaguari', 23),
	('Jaguaribe', 6),
	('Janduís', 20),
	('Japeri', 19),
	('Jaraguá do Sul', 24),
	('Jardim', 6),
	('Jardim de Piranhas', 20),
	('Jataúba', 16),
	('Jati', 6),
	('Jequitinhonha', 11),
	('Ji-Paraná', 21),
	('Joinville', 24),
	('João Pessoa', 15),
	('Juazeiro do Norte', 6),
	('Jucás', 6),
	('Juiz de Fora', 11),
	('Jundiaí', 26),
	('Juína', 13),
	('Ladário', 12),
	('Lagarto', 25),
	('Lages', 24),
	('Lagoa Nova', 20),
	('Lagoa Vermelha', 23),
	('Laguna', 24),
	('Laguna Carapã', 12),
	('Lajeado', 23),
	('Lapa', 18),
	('Laranjeiras do Sul', 18),
	('Laurentino', 24),
	('Lauro Muller', 24),
	('Lavras da Mangabeira', 6),
	('Liberato Salzano', 23),
	('Limoeiro', 16),
	('Limoeiro do Norte', 6),
	('Lindolfo Collor', 23),
	('Linhares', 8),
	('Londrina', 18),
	('Lontras', 24),
	('Lucas do Rio Verde', 13),
	('Luís Correia', 17),
	('Lábrea', 3),
	('Macapá', 4),
	('Macaé', 19),
	('Maceió', 2),
	('Machadinho', 23),
	('Madalena', 6),
	('Mafra', 24),
	('Manacapuru', 3),
	('Manaus', 3),
	('Manhuaçu', 11),
	('Manicoré', 3),
	('Manoel Viana', 23),
	('Mar de Espanha', 11),
	('Maracanaú', 6),
	('Maranguape', 6),
	('Maravilha', 24),
	('Marechal Cândido Rondon', 18),
	('Maringá', 18),
	('Massapê', 6),
	('Massaranduba', 24),
	('Mathias Lobato', 11),
	('Matões', 10),
	('Mauriti', 6),
	('Mauá', 26),
	('Maués', 3),
	('Medianeira', 18),
	('Meleiro', 24),
	('Mendes', 19),
	('Meruoca', 6),
	('Milagres', 6),
	('Minas do Leão', 23),
	('Mirassol', 26),
	('Mirim Doce', 24),
	('Missão Velha', 6),
	('Mococa', 26),
	('Modelo', 24),
	('Mombaça', 6),
	('Mondaí', 24),
	('Monsenhor Tabosa', 6),
	('Monte Alegre', 14),
	('Monte Alegre de Minas', 11),
	('Montenegro', 23),
	('Morro da Fumaça', 24),
	('Mossoró', 20),
	('Muçum', 23),
	('Nanuque', 11),
	('Natal', 20),
	('Navegantes', 24),
	('Naviraí', 12),
	('Nilópolis', 19),
	('Niterói', 19),
	('Nobres', 13),
	('Nortelândia', 13),
	('Nossa Senhora da Glória', 25),
	('Nova Andradina', 12),
	('Nova Esperança', 18),
	('Nova Hartz', 23),
	('Nova Iguaçu', 19),
	('Nova Mamoré', 21),
	('Nova Marilândia', 13),
	('Nova Mutum', 13),
	('Nova Odessa', 26),
	('Nova Olinda do Norte', 3),
	('Nova Olímpia', 13),
	('Nova Petrópolis', 23),
	('Nova Ponte', 11),
	('Nova Prata', 23),
	('Nova Prata do Iguaçu', 18),
	('Nova Russas', 6),
	('Nova Veneza', 24),
	('Nova Xavantina', 13),
	('Novo Aripuanã', 3),
	('Novo Hamburgo', 23),
	('Novo Oriente', 6),
	('Novo Repartimento', 14),
	('Não-Me-Toque', 23),
	('Olinda', 16),
	('Orleans', 24),
	('Osasco', 26),
	('Osório', 23),
	('Ouro Preto do Oeste', 21),
	('Ouro Verde', 26),
	('Pacatuba', 6),
	('Pacujá', 6),
	('Palhoça', 24),
	('Palmas', 18),
	('Palmeira dos Índios', 2),
	('Palmitos', 24),
	('Palmácia', 6),
	('Palotina', 18),
	('Panambi', 23),
	('Parambu', 6),
	('Paramoti', 6),
	('Paranaguá', 18),
	('Paranatinga', 13),
	('Paranavaí', 18),
	('Parelhas', 20),
	('Parintins', 3),
	('Parnamirim', 20),
	('Parnaíba', 17),
	('Passo Fundo', 23),
	('Passos', 11),
	('Pato Branco', 18),
	('Patos', 15),
	('Patos de Minas', 11),
	('Patrocínio', 11),
	('Paulista', 16),
	('Paulistana', 17),
	('Paulínia', 26),
	('Pedra Branca', 6),
	('Pejuçara', 23),
	('Penaforte', 6),
	('Penedo', 2),
	('Penha', 24),
	('Pesqueira', 16),
	('Petrolina', 16),
	('Peçanha', 11),
	('Picos', 17),
	('Pinhais', 18),
	('Pinhal Grande', 23),
	('Pinhalzinho', 24),
	('Pinheiro Preto', 24),
	('Piquet Carneiro', 6),
	('Piracicaba', 26),
	('Pirapora', 11),
	('Piratini', 23),
	('Pires do Rio', 9),
	('Piripiri', 17),
	('Planalto', 18),
	('Planalto', 23),
	('Pombal', 15),
	('Ponta Grossa', 18),
	('Ponta Porã', 12),
	('Ponte Nova', 11),
	('Pontes e Lacerda', 13),
	('Poranga', 6),
	('Porteiras', 6),
	('Porto Alegre', 23),
	('Porto União', 24),
	('Porto Velho', 21),
	('Posse', 9),
	('Potengi', 6),
	('Potiretama', 6),
	('Pouso Redondo', 24),
	('Poços de Caldas', 11),
	('Praia Grande', 26),
	('Presidente Figueiredo', 3),
	('Presidente Getúlio', 24),
	('Presidente Prudente', 26),
	('Quatis', 19),
	('Quinze de Novembro', 23),
	('Quiterianópolis', 6),
	('Quixadá', 6),
	('Quixeré', 6),
	('Realeza', 18),
	('Recife', 16),
	('Resende', 19),
	('Resplendor', 11),
	('Riacho de Santana', 20),
	('Ribeiro Gonçalves', 17),
	('Ribeirão Pires', 26),
	('Ribeirão Preto', 26),
	('Rio Claro', 26),
	('Rio Fortuna', 24),
	('Rio Grande', 23),
	('Rio Negrinho', 24),
	('Rio Pardo', 23),
	('Rio de Janeiro', 19),
	('Rio do Campo', 24),
	('Rio do Oeste', 24),
	('Rio do Sul', 24),
	('Rio dos Cedros', 24),
	('Rodeio', 24),
	('Rolim de Moura', 21),
	('Ronda Alta', 23),
	('Rondonópolis', 13),
	('Rosário do Sul', 23),
	('Russas', 6),
	('Ruy Barbosa', 5),
	('Sacramento', 11),
	('Salete', 24),
	('Salto Veloso', 24),
	('Salto do Jacuí', 23),
	('Salto do Lontra', 18),
	('Salvador do Sul', 23),
	('Salvaterra', 14),
	('Santa Bárbara do Sul', 23),
	('Santa Cruz das Palmeiras', 26),
	('Santa Cruz do Capibaribe', 16),
	('Santa Cruz do Sul', 23),
	('Santa Gertrudes', 26),
	('Santa Izabel do Oeste', 18),
	('Santa Juliana', 11),
	('Santa Luzia', 15),
	('Santa Maria', 23),
	('Santa Quitéria', 6),
	('Santa Rosa', 23),
	('Santa Rosa de Lima', 24),
	('Santa Vitória do Palmar', 23),
	('Santana', 4),
	('Santana do Acaraú', 6),
	('Santarém', 14),
	('Santiago', 23),
	('Santo Afonso', 13),
	('Santo Amaro das Brotas', 25),
	('Santo André', 26),
	('Santo Antônio da Patrulha', 23),
	('Santo Antônio do Içá', 3),
	('Santo Augusto', 23),
	('Santos', 26),
	('Saquarema', 19),
	('Saudades', 24),
	('Seara', 24),
	('Seberi', 23),
	('Segredo', 23),
	('Senador Sá', 6),
	('Serafina Corrêa', 23),
	('Seringueiras', 21),
	('Serra', 8),
	('Serra Negra do Norte', 20),
	('Siderópolis', 24),
	('Silves', 3),
	('Simplício Mendes', 17),
	('Sinop', 13),
	('Sobradinho', 23),
	('Sobral', 6),
	('Sobrália', 11),
	('Soledade', 23),
	('Sombrio', 24),
	('Sorriso', 13),
	('Soure', 14),
	('Sumaré', 26),
	('Surubim', 16),
	('São Bento do Sul', 24),
	('São Bernardo do Campo', 26),
	('São Borja', 23),
	('São Caetano do Sul', 26),
	('São Carlos', 24),
	('São Francisco de Assis', 23),
	('São Francisco do Sul', 24),
	('São Félix do Piauí', 17),
	('São Gabriel', 23),
	('São Gabriel do Oeste', 12),
	('São Geraldo do Baixio', 11),
	('São Gonçalo', 19),
	('São Gotardo', 11),
	('São Jerônimo', 23),
	('São José', 24),
	('São José do Ouro', 23),
	('São José do Rio Claro', 13),
	('São José do Rio Preto', 26),
	('São José do Seridó', 20),
	('São José dos Campos', 26),
	('São João de Meriti', 19),
	('São João del Rei', 11),
	('São João do Itaperiú', 24),
	('São João do Jaguaribe', 6),
	('São Leopoldo', 23),
	('São Lourenço do Oeste', 24),
	('São Ludgero', 24),
	('São Luiz Gonzaga', 23),
	('São Manuel', 26),
	('São Marcos', 23),
	('São Miguel do Guaporé', 21),
	('São Miguel do Oeste', 24),
	('São Paulo de Olivença', 3),
	('São Pedro da Aldeia', 19),
	('São Pedro do Sul', 23),
	('São Romão', 11),
	('São Sebastião', 26),
	('São Sepé', 23),
	('São Vicente', 26),
	('Tabuleiro do Norte', 6),
	('Taió', 24),
	('Tambaú', 26),
	('Tamboril', 6),
	('Tangará', 24),
	('Tangará da Serra', 13),
	('Tanguá', 19),
	('Tapejara', 23),
	('Tapera', 23),
	('Tapurah', 13),
	('Taquara', 23),
	('Taquari', 23),
	('Tatuí', 26),
	('Taubaté', 26),
	('Tauá', 6),
	('Tenente Portela', 23),
	('Teresina', 17),
	('Teresópolis', 19),
	('Terra Santa', 14),
	('Terra de Areia', 23),
	('Teutônia', 23),
	('Teófilo Otoni', 11),
	('Timbaúba', 16),
	('Timon', 10),
	('Timóteo', 11),
	('Toledo', 18),
	('Trairi', 6),
	('Treze de Maio', 24),
	('Trombudo Central', 24),
	('Três Cachoeiras', 23),
	('Três Coroas', 23),
	('Três Lagoas', 12),
	('Três Palmeiras', 23),
	('Três Passos', 23),
	('Tubarão', 24),
	('Tupaciguara', 11),
	('Tupanci do Sul', 23),
	('Tupanciretã', 23),
	('Turvo', 24),
	('Ubatuba', 26),
	('Uberlândia', 11),
	('Unistalda', 23),
	('União', 17),
	('União da Vitória', 18),
	('União do Sul', 13),
	('Urucurituba', 3),
	('Uruguaiana', 23),
	('Uruoca', 6),
	('Urupá', 21),
	('Urussanga', 24),
	('Vacaria', 23),
	('Vale Real', 23),
	('Vargeão', 24),
	('Varginha', 11),
	('Venâncio Aires', 23),
	('Vera Cruz', 23),
	('Veranópolis', 23),
	('Vespasiano', 11),
	('Viana', 8),
	('Vicente Dutra', 23),
	('Videira', 24),
	('Vila Rica', 13),
	('Vila Velha', 8),
	('Vilhena', 21),
	('Vitor Meireles', 24),
	('Vitória', 8),
	('Vitória da Conquista', 5),
	('Vitória de Santo Antão', 16),
	('Volta Redonda', 19),
	('Várzea Alegre', 6),
	('Várzea Grande', 13),
	('Xanxerê', 24),
	('Xaxim', 24),
	('Água Boa', 13),
	('Águas de Chapecó', 24),
	('Óbidos', 14);
