CREATE GROUP ADMINISTRADORES;

CREATE GROUP DEV;

CREATE GROUP USUARIO_BASE;

GRANT ALL PRIVILEGES ON DATABASE RESOLVE_AE TO ADMINISTRADORES;

GRANT SELECT ON DATABASE RESOLVE_AE TO DEV;

GRANT INSERT ON DATABASE RESOLVE_AE TO DEV;

GRANT UPDATE ON DATABASE RESOLVE_AE TO DEV;

GRANT CREATE ON DATABASE RESOLVE_AE TO DEV;

GRANT EXECUTE ON DATABASE RESOLVE_AE TO DEV;

GRANT SELECT ON DATABASE RESOLVE_AE TO USUARIO_BASE;