INSERT INTO subtipo_servico(nome, fk_tipo_servico) VALUES
	('Elaboração de Documentação', 1),
	('Levantamento de Requisitos', 1),
	('Modelagem de Sistemas', 1),
	('Administração de Banco de Dados', 2),
	('Análise de Banco de Dados', 2),
	('Análise de Business Intelligence', 2),
	('Ciência de Dados', 2),
	('Modelagem de Banco de Dados', 2),
	('Desenvolvimento Desktop', 3),
	('Desenvolvimento Mobile', 3),
	('Desenvolvimento Web', 3),
	('Frontend', 3),
	('Fullstack', 3),
	('Sistemas Embarcados', 3),
	('Design Gráfico', 4),
	('Design de Interface', 4),
	('Web Design', 4),
	('Atualização de Drivers/Firmware', 5),
	('Auditoria', 5),
	('Gerenciamento de Firewall', 5),
	('Hospedagem de Sistemas', 5),
	('Instalação de Servidores ou Dispositivos de Rede', 5),
	('Monitoramento', 5),
	('Problemas com Conexão', 5),
	('Problemas de Desempenho', 5),
	('Configuração e Gerencimento de Software', 6),
	('Configuração, Substituição e Análise de Hardware', 6),
	('Limpeza e Otimização de Computadores', 6),
	('Manutenção Preventiva e Corretiva', 6),
	('Administração de Rede de Computadores', 7),
	('Levantamento e Análise de Riscos', 7),
	('Otimização e Análise', 7),
	('Recuperação e Plano de Contingência', 7),
	('Análise de Processos', 8),
	('Auditoria e Análise de Riscos', 8),
	('Backup e Recuperação de Dados', 8),
	('Controle de Acesso à Infraestrutura', 8),
	('Gerenciamento de Redes', 8);
