CREATE TABLE tipo_servico(
	id SERIAL PRIMARY KEY, 
	nome VARCHAR (30) UNIQUE
);
INSERT INTO tipo_servico(nome) VALUES
	('MANUTENÇÃO E SUPORTE'),
	('REDE DE COMPUTADORES'),
	('BANCO DE DADOS'),
	('DESENVOLVIMENTO'),
	('DESIGN'),
	('ANÁLISE DE SISTEMA'),
	('SEGURANÇA DA INFORMAÇÃO');


