--VERIFICA SE O NOME DO SUB TIPO JA EXISTE ATRELADO AO TIPO DE SERVICO.
--CASO NAO EXISTA EH CRIADO UM.
CREATE FUNCTION TRATAMENTO_SUBSERVICO(NOME_SUB VARCHAR, ID_TIPO INTEGER)
  RETURNS VOID AS 
  $$
  BEGIN
IF (SELECT COUNT(*) FROM SUBTIPO_SERVICO WHERE NOME LIKE NOME_SUB AND FK_TIPO_SERVICO = ID_TIPO) = 0 THEN
  INSERT INTO SUBTIPO_SERVICO(NOME,FK_TIPO_SERVICO) VALUES(NOME_SUB, ID_TIPO);
END IF;
  END;
$$ LANGUAGE plpgsql;
